'use strict';
var color = prompt('What is your favorite color?');
alert('I like ' + color + ' too.');
console.log(color);
var flavor = prompt('What is your favorite flavor');
alert('I like ' + flavor + ' too.');
console.log(flavor);
var hobby = prompt('What is your favorite hobby?');
alert('I like ' + hobby + ' too.');
console.log(hobby);
var sport = prompt('What is your favorite sport?');
alert('Wow, I like all your choices!' + ' ' + color + ' ' + flavor + ' ' + hobby + ' ' + sport );
console.log(sport);
